### ISSUE TITLE
Submit to Nimble

### ISSUE THREAD

**Issue by capocasa** [aspiring-aster/twim#1]
Hello!

Just tried your client. Worked out of the box. Great!!!

Please make a nimble package and submit to the nimble directory! It would make a huge difference to the Nim ecosystem to have a working Twitter/X package. Thanks!!!

https://github.com/nim-lang/packages/

**Comment by aspiring-aster** [comment]
Thank you! I will plan to do that by the start of December. I've been very busy, and I saw that there's Twitter/X API changes that grants more endpoints to free users. I'd love to add those endpoints before publishing this package.

I'm glad someone outside of myself has found a use for this package. I'll be sure to update soon and then publish the 1.0 version of it!

**Comment by capocasa** [comment]
Great!!! Thanks for your feedback. Just a suggestion- release it _before_ you add the endpoints! It's really very useful the way ouit is. Then you can do another release with the new endpoints and you can post it in the forum twice and get a little extra buzz ;)

**Comment by aspiring-aster** [comment]
Thank you for the suggestion and motivation to continue with this project! I've drafted the PR to get this added to the nim packages. I'll close this issue once it's been accepted! I'll continue to flesh out this project in the mean time!

**Comment by aspiring-aster** [comment]
It's been published!

**Comment by capocasa** [comment]
Yeah!!! All right, congratulations!

Just another suggestion- make a quick "announce" post on forum.nim-lang.org just so folks know there is a working nim twitter client. Makes it easier to find if someone's looking...
